{
 "title": "Windows Server",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(windows_cs_hostname,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max (windows_os_info{hostname=\"$hostname\"}) by (hostname,product,version)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (time()-windows_system_system_up_time{hostname=\"$hostname\"}) by (hostname)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (windows_cs_logical_processors{hostname=\"$hostname\"}) by (hostname)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (windows_cs_physical_memory_bytes{hostname=\"$hostname\"}) by (hostname)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% CPU Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "100-(rate(windows_cpu_time_total{hostname=\"$hostname\",mode=\"idle\"}[$__rate_interval])*100)",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "% RAM Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "100.0-100 * windows_os_physical_memory_free_bytes{hostname=\"$hostname\"} / windows_cs_physical_memory_bytes{hostname=\"$hostname\"}",
     "legendFormat": "Memory use"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{hostname=\"$hostname\",nic!~\"(^isatap.*$)\"}[$__rate_interval])",
     "legendFormat": "{{nic}} Rcvd"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total{hostname=\"$hostname\",nic!~\"(^isatap.*$)\"}[$__rate_interval])",
     "legendFormat": "{{nic}} Sent"
    }
   ]
  },
  {
   "title": "Disk Used Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (windows_logical_disk_free_bytes{hostname=\"$hostname\",volume=~\"(^.:$)\"} / windows_logical_disk_size_bytes{hostname=\"$hostname\",volume=~\"(^.:$)\"})) * 100    ",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Read/Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(windows_logical_disk_write_bytes_total{hostname=\"$hostname\",volume=~\"(^.:$)\"}[$__rate_interval])",
     "legendFormat": "{{volume}} write"
    },
    {
     "expr": "rate(windows_logical_disk_read_bytes_total{hostname=\"$hostname\",volume=~\"(^.:$)\"}[$__rate_interval])",
     "legendFormat": "{{volume}} read"
    }
   ]
  }
 ]
}